### ISSUE TITLE
Question about the make_model

### ISSUE THREAD

**Issue by viet2411** [mode-str/crossview#7]
Hello,
Thank you for your work. I really appreciate it.
I tried to reproduce the result again, but I got this error:

`  File "E:\Downloads\MCCG\models\ConvNext\make_model.py", line 199, in forward
    gap_feature, part_features = self.convnext(x)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)`

I think the ConvNext model return only 1 feature, but in your code it was different.
Can you review this for me?

Thank you and best regards!

**Comment by mode-str** [comment]
The _self.convnext(x)_ function returns two values, see Line 118 of the file _model_convnext.py_.

**Comment by viet2411** [comment]
Thank you for your answer.
I was able to run the code, but the loss value returned NaN
Do you have any idea about the reasons behind this?

![image](https://github.com/user-attachments/assets/86e64af3-004f-4a52-bec3-a06b53ee9aaa)

**Comment by viet2411** [comment]
![image](https://github.com/user-attachments/assets/4575e9f5-3ea1-49a4-8ee9-fc8386718e14)

**Comment by mode-str** [comment]
This looks weird. Did you make any changes to the code?

**Comment by viet2411** [comment]
Yes. 
1. When I run the code, autoaugment can not be used because of the following error: np.int can not be used
![image](https://github.com/user-attachments/assets/f155ab1d-744f-49d1-a02f-a6bb26b23602)
so I changed line 236 in the **autoaugment.py** (np.int => int)
![image](https://github.com/user-attachments/assets/fce50b61-f15b-41f2-9f94-301f9920c8c6)
2. timm's model can not be used because I got this error:
![image](https://github.com/user-attachments/assets/88534f27-2514-407b-940c-8aa691e1547b)
so instead of using timm's create_model method, I use the convnext_tiny from the **model_convnext.py**:
![image](https://github.com/user-attachments/assets/1bc3d5df-dd83-4e45-854a-a2107bc7014d)

3.The code can not automatically download the weights, so I manually downloaded the weights from the URLs and modified the code in the **model_convnext.py**:
![image](https://github.com/user-attachments/assets/9d68ecb4-93e6-410c-a0d6-f5eac6919c0a)

**Comment by mode-str** [comment]
I guess it is caused by the change in line 236 in the autoaugment.py because you changed the data type. Have you tried changing it to np.int32 or np.int64?

**Comment by viet2411** [comment]
Thank you for your reply.
I changed it to np.int64 and it worked normally.
